Garbage collection and bug fixes
Distributed-EPFL/contagion pull request #4
Opened 2021-06-17 10:28 UTC by SonicFrog

Fixes issues when using agents from sieve and implements garbage collection for contagion

2021-06-17 10:51 UTC, tharvik approved these changes

2021-06-22 11:40 UTC, tharvik approved these changes
> codecov/patch: 79.52% of diff hit (target 80.00%)

2021-06-22 11:45 UTC, SonicFrog commented
Yeah should be fixed once I push the new tests

2021-06-23 10:27 UTC, tharvik requested changes

2021-06-23 10:27 UTC, tharvik commented on src/lib.rs
> +                    println!("{:?}", delivered);
debug?

2021-06-23 10:27 UTC, tharvik commented on src/lib.rs
> +                println!("adding {} new sequences", delivery.len());
debug?

2021-06-23 10:27 UTC, tharvik commented on src/lib.rs
> +            println!("final delivery: {:?}", empty);
debug?

2021-06-23 10:27 UTC, tharvik commented on src/lib.rs
> +            assert!(empty.is_empty());
look like you're testing the library outside of `cfg(test)`

2021-06-23 11:35 UTC, tharvik approved these changes

2021-06-23 11:43 UTC, merged